### ISSUE TITLE
Generate XML Schema 1.1 for IWXXM 3.0

### ISSUE THREAD

**Issue by marqh** [wmo-im/AvXML#4]
Instead of generating IWXXM 2.0 in XML Schema 1.1 this ticket previously mentioned, it will be more beneficial to have this in upcoming pre-release version of IWXXM (viz 3.0RC1) and be published well before the next Annex 3 amendment cycle for technology preview and testing.

ref: https://software.ecmwf.int/issues/browse/AVXML-7

Created:
    29/Sep/15 7:08 PM 

Reporter:
    Aaron Braeckel

**Comment by braeckel** [comment]
There are two advantages to XML Schema 1.1:

 - the open content model
 - putting rules directly in the schema, instead of having a Schematron and XML Schema definition that both are checked

The open content model advantages have essentially been met through the use of extensions.  The rules directly in the schema are an advantage but do not overcome the lack of implementation of XML Schema 1.1 among users.   If there is another request for this at a later date it will be considered, but is not considered important for now.
